import { Product } from "@/interfaces/product.interface";

export const mockData: Product[] = [
  {
    id: 1,
    title: "Product 1",
    description: "Description for Product 1",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$100",
  },
  {
    id: 2,
    title: "Product 2",
    description: "Description for Product 2",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$300",
  },
  {
    id: 3,
    title: "Product 3",
    description: "Description for Product 3",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$10",
  },
  {
    id: 4,
    title: "Product 4",
    description: "Description for Product 4",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$200",
  },
  {
    id: 5,
    title: "Product 5",
    description: "Description for Product 5",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$500",
  },
  {
    id: 6,
    title: "Product 6",
    description: "Description for Product 6",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$400",
  },
  {
    id: 7,
    title: "Product 7",
    description: "Description for Product 7",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$800",
  },
  {
    id: 8,
    title: "Product 8",
    description: "Description for Product 8",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$600",
  },
  {
    id: 9,
    title: "Product 9",
    description: "Description for Product 9",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$900",
  },
  {
    id: 10,
    title: "Product 10",
    description: "Description for Product 10",
    image: "https://placehold.co/400/png",
    category: "Test",
    price: "$700",
  },
];
